version: "2.2"
services:
  db:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pandora_db
      MYSQL_USER: pandora
      MYSQL_PASSWORD: pandora
    image: percona:5.7
    networks:
      default:
        aliases:
          - pandora-db-01
